"""update employee model

Revision ID: 16fbffab3d40
Revises: fa4413580d52
Create Date: 2026-07-12 23:14:57.297131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16fbffab3d40'
down_revision: Union[str, Sequence[str], None] = 'fa4413580d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_code', sa.String(length=30), nullable=False))
    op.add_column('employees', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('employees', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('employees_employee_id_key'), 'employees', type_='unique')
    op.create_unique_constraint(None, 'employees', ['employee_code'])
    op.drop_column('employees', 'full_name')
    op.drop_column('employees', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_id', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='unique')
    op.create_unique_constraint(op.f('employees_employee_id_key'), 'employees', ['employee_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    op.drop_column('employees', 'employee_code')
    # ### end Alembic commands ###
